name: SSMasterLibForm
---
SSMasterLibForm:
  inline_fields:
    - CheckboxField
    - FormAction
FormField:
  extensions:
    - SSMasterLibFormField
FileField:
  extensions:
    - SSMasterLibFileField
TextField:
  extensions:
    - SSMasterLibTextField
DropdownField:
  extensions:
    - SSMasterLibDropdownField
OptionsetField:
  extensions:
    - SSMasterLibOptionsetField
FormAction:
  extensions:
    - SSMasterLibFormAction
FieldList:
  extensions:
    - SSMasterLibFieldList
Injector:
  MemberLoginForm:
    class: SSMasterLibMemberLoginForm
  Security:
    class: SSMasterLibSecurity
---
only:
  moduleexists: userforms
---
UserDefinedForm_Controller:
  extensions:
    - SSMasterLibUserForm
