name: SSMasterLibForm
---
CatchDesign\SSMasterLibForms\SMasterLibForm:
  inline_fields:
    - CheckboxField
    - FormAction
SilverStripe\Forms\FormField:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibFormField
SilverStripe\Forms\FileField:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibFileField
SilverStripe\Forms\TextField:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibTextField
SilverStripe\Forms\DropdownField:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibDropdownField
SilverStripe\Forms\OptionsetField:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibOptionsetField
SilverStripe\Forms\FormAction:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibFormAction
SilverStripe\Forms\FieldList:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibFieldList
Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: CatchDesign\SSMasterLibForms\SSMasterLibMemberLoginForm
  SilverStripe\Security\Security:
    class: CatchDesign\SSMasterLibForms\SSMasterLibSecurity
---
only:
  moduleexists: userforms
---
UserDefinedForm_Controller:
  extensions:
    - CatchDesign\SSMasterLibForms\SSMasterLibUserForm
